// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Laborator_ISP;

/************************************************************/
/**
 * 
 */
class Vechicul {
	
	public void Vehicul(int viteza, String mod) {
	
		this.vitezaMaxima=viteza;
		this.model=mod;
		
		
	}
	/**
	 * 
	 */
	protected int vitezaMaxima;
	/**
	 * 
	 */
	protected String model;

	/**
	 * 
	 */
	public void afisare() {
		System.out.println("Afisare vehicul");
	}
};
